<?php

namespace Tutorial\Trunghn\Model\ResourceModel\Faq;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id_faq';

    protected function _construct()
    {
        $this->_init(
            'Tutorial\Trunghn\Model\FAQ',
            'Tutorial\Trunghn\Model\ResourceModel\Faq'
        );
    }

//    protected function _initSelect()
//    {
//        $this->addFilterToMap('id', 'tutorial.id');
//        return $this; // TODO: Change the autogenerated stub
//    }
}
