<?php

namespace Tutorial\Trunghn\Model\ResourceModel\FaqStore;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';


    protected function _construct()
    {
        $this->_init(
            'Tutorial\Trunghn\Model\FAQStore',
            'Tutorial\Trunghn\Model\ResourceModel\FAQStore'
        );
    }

//    protected function _initSelect()
//    {
//        $this->addFilterToMap('id', 'tutorial_trunghn.id');
//        return $this; // TODO: Change the autogenerated stub
//    }
}
